version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password 

  php:
      image: php:7-fpm-alpine
      container_name: vibie-live-website-php7-alping
      volumes:
          - ./code:/code
      ports:
          - "9000:9000"

  nginx:
        image: nginx:stable-alpine
        container_name: EXAMPLE_PROJECT_NGINX
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

volumes:
    db_data:
